### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by PabloCastellano** [dlrust/python-memcached-stats#5]
This tool is very useful and it would be awesome to have Python 3 support on it!

**Comment by vanipolnedi** [comment]
>>> from memcached_stats import MemcachedStats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/memcached_stats.py", line 6
    _key_regex = re.compile(ur'ITEM (.*) \[(.*); (.*)\]')
                                                       ^
SyntaxError: invalid syntax


any suggestions please ??

**Comment by berislavlopac** [comment]
I believe this can be closed, as it's working fine with Python 3.7.5

**Comment by cn0047** [comment]
@berislavlopac It won't work on `Python 3.7.7`.

````sh
python3
Python 3.7.7 (default, Mar 10 2020, 15:43:33)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from memcached_stats import MemcachedStats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/memcached_stats.py", line 6
    _key_regex = re.compile(ur'ITEM (.*) \[(.*); (.*)\]')
                                                       ^
SyntaxError: invalid syntax
>>>
````

Here all my steps:

````sh
m@k gh % pip3 install 'git+git://github.com/dlrust/python-memcached-stats.git'
Collecting git+git://github.com/dlrust/python-memcached-stats.git
  Cloning git://github.com/dlrust/python-memcached-stats.git to /private/var/folders/cp/d7_wlw3x3j90j7360c4vljyh0000gn/T/pip-req-build-eh96_bde
  Running command git clone -q git://github.com/dlrust/python-memcached-stats.git /private/var/folders/cp/d7_wlw3x3j90j7360c4vljyh0000gn/T/pip-req-build-eh96_bde
Requirement already satisfied (use --upgrade to upgrade): python-memcached-stats==0.1 from git+git://github.com/dlrust/python-memcached-stats.git in /usr/local/lib/python3.7/site-packages
Building wheels for collected packages: python-memcached-stats
  Building wheel for python-memcached-stats (setup.py) ... done
  Created wheel for python-memcached-stats: filename=python_memcached_stats-0.1-py3-none-any.whl size=2101 sha256=5190d32e9d15c5073ff4f12d35e8834b44ae2335ac10b0b61ebc4a80181dc39a
  Stored in directory: /private/var/folders/cp/d7_wlw3x3j90j7360c4vljyh0000gn/T/pip-ephem-wheel-cache-pdeajx57/wheels/2e/1e/b9/dbbacfcb0f95fb2d50cc04ef0a58b3683b9ff46e4d470e0ebc
Successfully built python-memcached-stats
m@k gh %
m@k gh % python3
Python 3.7.7 (default, Mar 10 2020, 15:43:33)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from memcached_stats import MemcachedStats
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/memcached_stats.py", line 6
    _key_regex = re.compile(ur'ITEM (.*) \[(.*); (.*)\]')
                                                       ^
SyntaxError: invalid syntax
>>>
````

**Comment by skabbit** [comment]
This repo works well on Python 3.7.6. 
It's just need to be updated on pip.

**Comment by LuisGomez24** [comment]
@cn007b I am late, but here is what I did to solve this problem with regex memcached_stats. 

The problem is regex code, where clause 'ur' is deprecated since PEP 414. You need to use 'r' instead. 
Source: https://peps.python.org/pep-0414/
